name       : mygui
version    : 3.4.1
release    : 9
source     :
    - https://github.com/MyGUI/mygui/archive/refs/tags/MyGUI3.4.1.tar.gz : bdf730bdeb4ad89e6b8223967db01aa5274d2b93adc2c0d6aa4842faeed4de1a
license    : MIT
component  : programming.library
summary    : MyGUI is a cross-platform library for creating graphical user interfaces
description: |
    MyGUI is a cross-platform library for creating graphical user interfaces
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
setup      : |
    %cmake_ninja \
        -DMYGUI_BUILD_DEMOS=OFF \
        -DMYGUI_BUILD_PLUGINS=OFF \
        -DMYGUI_BUILD_TOOLS=OFF \
        -DMYGUI_RENDERSYSTEM=4 \
        -DMYGUI_USE_SYSTEM_GLEW=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
