name       : mygui
version    : 3.2.2
release    : 5
source     :
    - https://github.com/MyGUI/mygui/archive/MyGUI3.2.2.tar.gz : 0a28d7ec8a47993cb68deb48b36331e28f12dd92580b709eaef21d599b67a78f
license    : MIT
component  : programming
summary    : MyGUI is a cross-platform library for creating graphical user interfaces
description: |
    MyGUI is a cross-platform library for creating graphical user interfaces
libsplit   : no
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(OGRE)
    - pkgconfig(OIS)
    - libboost-devel
setup      : |
    %cmake -DMYGUI_RENDERSYSTEM=3 \
           -DMYGUI_BUILD_DEMOS=0 \
           -DMYGUI_USE_SYSTEM_GLEW=1 \
           -DMYGUI_HIGH_LEVEL_WARNINGS=0 \
           .
build      : |
    %make
install    : |
    %make_install
