name       : mygui
version    : 3.4.0
release    : 7
source     :
    - https://github.com/MyGUI/mygui/archive/MyGUI3.4.0.tar.gz : d1d5f294670ae71f7200ed4b30859018281d8cfd45d6a38d18b97a4aba604c42
license    : MIT
component  : programming.library
summary    : MyGUI is a cross-platform library for creating graphical user interfaces
description: |
    MyGUI is a cross-platform library for creating graphical user interfaces
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
setup      : |
    %cmake_ninja \
        -DMYGUI_BUILD_DEMOS=OFF \
        -DMYGUI_BUILD_PLUGINS=OFF \
        -DMYGUI_BUILD_TOOLS=OFF \
        -DMYGUI_RENDERSYSTEM=4 \
        -DMYGUI_USE_SYSTEM_GLEW=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
